### ISSUE TITLE
Dashboard login

### ISSUE THREAD

**Issue by YaManicKill** [DerEnderKeks/Yanius#29]
Hi guys,

I tried to find this info in your docs and couldn't find it anywhere. Where do we set/get the credentials for the dashboard first time?

Thanks.

**Comment by DerEnderKeks** [comment]
Hello,

the default credentials are:
User: `admin`
Password: `12345678`

Iirc those credentials are printed to the console during the first run but I'm not sure.
(Note: You may have to tick the `Stay signed in` checkbox as there currently is a bug with the sessions)

Regards 
DerEnderKeks

**Comment by YaManicKill** [comment]
Thanks, I did look to see if that had happened, but I couldn't see it. I might have missed it because of #30
