### ISSUE TITLE
Some images fail to upload with 413

### ISSUE THREAD

**Issue by Makeshift** [DerEnderKeks/Yanius#34]
```
Response:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

I'm also unable to upload said file through the web interface: `Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`
I've tried uploading via sharex as a file and a selected area screenshot.

This is the image in question: https://s.makeshift.ninja/Capture.PNG , though I've encountered several times when trying to upload images. Is there an image file size limit?

Settings are set with the max file size and max quota at the top end, 100gb/1tb.

**Comment by DerEnderKeks** [comment]
That's a a problem with your nginx configuration.

You have to increase [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).

**Comment by Makeshift** [comment]
Whoops! You are indeed correct, my bad.

Problem solved by adding `client_max_body_size 100G` to my reverse proxy config in nginx (though I wouldn't generally advise having it that high)
